package:
  name: metamds-dev
  version: !!str 0.1.0.dev0

requirements:
  build:
    - python

  run:
    - python

test:
  requires:
    - pytest
  commands:
    - py.test -v --pyargs metamds

about:
  home: http://imodels.github.io/metamds
  license: MIT
  summary: Coming soon
